service: sls-advent-template
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  profile: ${env:AWS_PROFILE, 'default'}
  region: ${opt:region, 'ap-southeast-2'}
  environment:
    SERVICE_STAGE: ${self:provider.stage}
    APP_URL: ${env:APP_URL}
    MONGO_URI: ${env:MONGO_URI}
    
custom:
  customDomain:
    domainName: ${env:APP_URL}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: REGIONAL
    apiType: http

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-domain-manager
